[tool]
[tool.poetry]
authors = ["Renan Pires <renan.sp.121@hotmail.com>"]
name = "root"
version = "0.0.0"
description="flask template"
[tool.poetry.dependencies]
flask = "==1.1.2"
python = "^3.11"
requests = "^2.31.0"
